version: '3.8'

services:
  db:
    image: mysql:8.0  #ปรับเป็น mysql:8.0 เพื่อใช้ MySQL เวอร์ชัน 8.0
    container_name: mysql_db_700
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8700:8700"
    volumes:
      - mysql_data_700:/var/lib/mysql
    networks:
      - weblab700
    restart: always

  phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  environment:
    PMA_HOST: db
    PMA_USER: root
    PMA_PASSWORD: root
    UPLOAD_LIMIT: 64M
  ports:
    - "8701:80"
  depends_on:
    - db
  networks:
    - weblab700
  restart: always

  
volumes:
  mysql_data_700:
    driver: local